In [1]:
# import required python libraries
%matplotlib inline
import numpy as np
import scipy
import random
import matplotlib.pylab as plt 
import seaborn as sns

# Variables and standard math operations
Python has the usual suspects in terms of math operations.

In [2]:
a = 5
b = 4
print(a+b)
print(a-b)
print(a*b)
print(a/b)

9
1
20
1.25


As you can appreciate from the last operation, python handily deals with floating point numbers (i.e., numbers with decimals). Here's another example:

In [3]:
c = 2.4
d = 1.5
f = c*d
print(f)

3.5999999999999996


One tricky math operation in python is raising to a power. This can be accomplished in two ways:

In [19]:
a = 2.0
b = a**2
print(b)
c = pow(a,2)
print(c)

d = a**(0.5) # how about taking the square root? (same as raising to the 1/2 power)
print(d)

4.0
4.0
1.4142135623730951


# Lists
Lists allow you to store multiple values in one variable.

In [5]:
g = [1,2,3]
print(g)

[1, 2, 3]


Items can be added to list with the `append` function

In [6]:
g.append(28)
print(g)

[1, 2, 3, 28]


To index a list, use brackets and the location of the value you want to retrieve (NOTE: python uses 0 as the first index).

In [7]:
print(g[0])

1


You can change the value at a specific location in a list by using its index.

In [8]:
print(g)
g[1] = 14
print(g)

[1, 2, 3, 28]
[1, 14, 3, 28]


# Numpy arrays
Numpy is a python library that provides a host of numerical functions and data types that make computations much easier. One critical aspect of numpy is its arrays. Arrays are similar to lists, but can handle elementwise computations.

In [9]:
# here's a list
a = [1,2,3]
# what do you think is going to happen?
b = a*3
print(b)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


Probably not what you had in mind. Using the multiplication operator with a list creates a new list that repeats the original list the specified number of times. Let's try a numpy array instead.

In [10]:
# here's a numpy array
c = np.array([1,2,3])
d = c*3
print(d)

[3 6 9]


That's better. Note the use of the shorthand `np` before the array function. Way back at the top, I imported numpy and gave it a shorthand name of np (e.g., `import numpy as np`). This lets me use `np` instead of `numpy` to access numpy's functions.

Numpy arrays are indexed in the same way as lists:

In [11]:
print(d[2])
d[0] = d[0]+2
print(d)

9
[5 6 9]


Broadcasting is a useful way to index the value in multiple locations of a numpy arrays:

In [12]:
a = np.array([0,1,2,3,4,5,6])
print(a[2:5]) # elements from index 2 to index 5 (but don't include value at index 5)
print(a[4:]) # elements from index 4 to end of array
print(a[:3]) # elements from beginning to index 3 (but don't include value at index 3)

[2 3 4]
[4 5 6]
[0 1 2]


Numpy provides several functions for creating different kinds of arrays:

In [13]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"

b = np.ones((1,2))   # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7) # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

d = np.eye(2)        # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"
    
e = np.random.random((2,2)) # Create an array filled with random values
print(e)  

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.66963711 0.25493759]
 [0.60947337 0.41084681]]


In [14]:
# indexing into a multidimensional array
print(e[0][1])

0.25493759299035734


In [15]:
# array operations
print(c+e)
print(c/e)
print(c*e)

[[7.66963711 7.25493759]
 [7.60947337 7.41084681]]
[[10.45342298 27.45770021]
 [11.48532551 17.0379808 ]]
[[4.6874598  1.78456315]
 [4.26631356 2.87592765]]


# Flow control
Python includes many of the standard code flow control mechanisms, including if-else statements and for/while loops:

In [16]:
a = 1
if a==1:
    b = 2
else:
    b = 3
print(b)

2


In [17]:
a=2
if a!=1: # assess if a variable is NOT equal to a value
    b = 2
else:
    b = 3
print(b)

2


In [18]:
a = 1
b = 2
if a==1:
    if b==1:
        c = 1
    elif b==2: # elif stands for else if
        c = 3
else:
    c = 2
print(c)

3
